language: R
sudo: false
cache: packages
warnings_are_errors: true

r:
- release
- devel
after_success:
- Rscript -e 'covr::codecov()'

notifications:
  slack:
    rooms:
      secure: hsavveG+2dweIcavAroyXamoFJySctT6pg0I+uI3hIfcyzL80W8BzCLD9aUH46xKbFxPTN3+LVJVUF80fKO/90EzsGhpWfpMw5XyKF6ybDwRzvD4ErNqKABGVddOEVpZpdmgjOyJJtLn60CLmVM8Bxqxu2QfxSoVYonryuj9ESHylBhGgbZgnlbiPM/BCsARct/qy+n+A4ApNiB3CU59E57oM9i6FSfxSzoYJnGMe1EaJtgYgHsgEJxm8I3xo1pCS1x0v2sDCBzHTJzgMqS4ZLqdZ1xpVQN2tteWdT1+VQl8stlS8nO2rdelJBfyp95mcXwCwackpf8dQCSaFt+5IHh8/xLuIa0+Dfde310e1HB+OoGZBEoEPSe1oU49NzIEwyl51QtDZy++APcVfhswWlNAVgKDnvfWYtRd/iGU0HEJA/QSLDypaHua2zxJIfAqmf37/veNXUBJH+tQMxeP8aAE2CShvnT8LQWJj9DD/TpLVX6FJ7LWl2/aitDP4Kw3DFgYwujA8kkrCPsG8ik4dWJWqg5fuML9qsLgsAhUj5NCYeY7IRQIIDR9vr/Eb0AtXzJ/ecWF0d66ifayFTs0l4cfWHXyPqq8WDcA6zJiU6HhWhwQ2MM/iAQZJCGhiXYBcv9YNHHobvW97OiGCBNAQusx66QD0bcTkJBhtPkcHrg=
    on_success: change
    on_failure: change
